wordpress:
  replicaCount: 2
  persistence:
    enabled: true
    size: 10Gi

mysql:
  persistence:
    enabled: true
    size: 20Gi

nginx:
  replicaCount: 2

ingress:
  enabled: true
  host: wordpress.localhost

hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 75