apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}-wordpress
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.wordpress.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: wordpress
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/component: wordpress
        {{- include "wordpress.labels" . | nindent 8 }}
    spec:
      containers:
        - name: wordpress
          image: "{{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}"
          imagePullPolicy: {{ .Values.wordpress.image.pullPolicy }}
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ include "wordpress.fullname" . }}-mysql
            - name: WORDPRESS_DB_USER
              value: {{ .Values.mysql.auth.user }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.mysql.auth.password }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.mysql.auth.database }}
          ports:
            - containerPort: 9000
          {{- if .Values.wordpress.persistence.enabled }}
          volumeMounts:
            - name: wp-data
              mountPath: /var/www/html/wp-content
          {{- end }}
      {{- if .Values.wordpress.persistence.enabled }}
      volumes:
        - name: wp-data
          persistentVolumeClaim:
            claimName: {{ include "wordpress.fullname" . }}-wp-pvc
      {{- end }}