apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}-wordpress
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: wp
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app.kubernetes.io/component: wordpress
    app.kubernetes.io/instance: {{ .Release.Name }}